language: c

before_install:
#  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - curl -OL http://raw.github.com/lcolladotor/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
 
install:
  - ./travis-tool.sh install_bioc S4Vectors
  - ./travis-tool.sh install_bioc IRanges
  - ./travis-tool.sh install_r Matrix
  - ./travis-tool.sh install_r knitr
  - ./travis-tool.sh install_r rmarkdown
  - ./travis-tool.sh install_r knitcitations
  - ./travis-tool.sh install_r knitrBootstrap
  - ./travis-tool.sh install_github lcolladotor/derfinderHelper
  - ./travis-tool.sh install_github lcolladotor/derfinderData
  - ./travis-tool.sh install_bioc_deps
 
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_script:
  - ./travis-tool.sh dump_logs_by_extension "timings"
  - ./travis-tool.sh dump_sysinfo

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: FIA40TI4UkOHvR19rNCfX1la5tiCmyEMjiO/sGyK0cWGt5qQxIOp+PHE3pOk9axYiVacbSCR3oAosQUsOxRew/6FyMsNR3bCPXVUzrIimABvBbjofMBDx3Z7W03O+6YahmHwDrJEWDuJ0k4457QqeqhITcFWX4twieo5fJCjedI=

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual --no-resave-data"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"
